; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\cygwin\home\uejima\PDFLibNet\libAFPDFLib\globals.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat


PUBLIC	?gStreamMutex@@3U_RTL_CRITICAL_SECTION@@A	; gStreamMutex
	ALIGN	4

?gStreamMutex@@3U_RTL_CRITICAL_SECTION@@A DB 018H DUP (?) ; gStreamMutex
	ORG $+280108
__bad_alloc_Message DD FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
PUBLIC	?InitGlobals@@YAXXZ				; InitGlobals
; Function compile flags: /Ogtpy
; File c:\cygwin\home\uejima\pdflibnet\libafpdflib\globals.cpp
;	COMDAT ?InitGlobals@@YAXXZ
_TEXT	SEGMENT
?InitGlobals@@YAXXZ PROC				; InitGlobals, COMDAT

; 6    : 	//Init global vars
; 7    : 	gInitMutex(&gStreamMutex);

	push	OFFSET ?gStreamMutex@@3U_RTL_CRITICAL_SECTION@@A ; gStreamMutex
	call	DWORD PTR __imp__InitializeCriticalSection@4

; 8    : }

	ret	0
?InitGlobals@@YAXXZ ENDP				; InitGlobals
END
